apiVersion: v1 
kind: ConfigMap
metadata:
  name: vote-app-config
data:
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"